---
- name: Run dstat on the minion prior to minion install
  include_role:
    name: validate-perf
  when: step_install_minion|bool

- name: Install the minion
  shell: >
    set -o pipefail &&
    {{ working_dir }}/minion-install.sh 2>&1 {{ timestamper_cmd }} >
    {{ minion_install_log }}
  when: step_install_minion|bool
