---
- name: Set the download url if amphora_url provided
  set_fact:
    download_url: "{{ amphora_url }}"
  when:
    amphora_url is defined and ((amphora_url | length) > 0)

- name: Set the download url to specified release branch if amphora_url not provided
  set_fact:
    download_url: "https://images.rdoproject.org/octavia/{{ release }}/amphora-x64-haproxy-centos.qcow2"
  when:
    download_url is not defined

- name: check for target directory for amphora image
  stat:
    path: "{{ octavia_amphora_path | dirname }}"
  register: amphora_path_stat_result

# We check for an existing directory because we do not want to modify
# permissions on existing directories, potentially causing perm issues
# with other tasks/processes.
- name: If target path does not exist, create as readable to everyone.
  file:
    path: "{{ octavia_amphora_path | dirname }}"
    state: directory
    mode: 0755
  become: true
  when:
    - not amphora_path_stat_result.stat.exists|bool

- name: Download the amphora
  get_url:
    url: "{{ download_url }}"
    dest: "{{ octavia_amphora_path }}"
    mode: 0644
  become: true
