---
- name: "Check if {{ containers_file }} exists"
  stat:
    path: "{{ working_dir }}/{{ containers_file }}"
  register: stat_cont_file

- name: "Render {{ containers_file }} if it doesn't exist."
  include_role:
    name: undercloud_deploy
    tasks_from: create-scripts.yml
  when: not stat_cont_file.stat.exists

- name: "Substitute containers registry to {{ docker_registry_host|default('nothing') }}/{{ docker_registry_namespace_used|default('nothing') }}"
  replace:
    path: "{{ working_dir }}/{{ containers_file }}"
    regexp: '^(\s*namespace:).*'
    replace: "\\1 {{ docker_registry_host }}/{{ docker_registry_namespace_used }}"
  when:
    - docker_registry_host is defined
    - docker_registry_namespace_used is defined

- name: "Substitute tag to {{ container_build_id|default('nothing') }}"
  replace:
    path: "{{ working_dir }}/{{ containers_file }}"
    regexp: '^(\s*tag:).*'
    replace: "\\1 {{ container_build_id }}"
  when: container_build_id is defined

- name: "Substitute name_prefix to {{ docker_prep_prefix|default('nothing') }}"
  replace:
    path: "{{ working_dir }}/{{ containers_file }}"
    regexp: '^(\s*name_prefix:).*'
    replace: "\\1 {{ docker_prep_prefix }}"
  when: docker_prep_prefix is defined

- name: "Substitute ceph_namespace to {{ docker_ceph_image|default('nothing') }}"
  replace:
    path: "{{ working_dir }}/{{ containers_file }}"
    regexp: '^(\s*ceph_namespace:).*'
    replace: "\\1 {{ docker_ceph_namespace }}"
  when: docker_ceph_namespace is defined

- name: "Substitute ceph_tag to {{ docker_ceph_tag|default('nothing') }}"
  replace:
    path: "{{ working_dir }}/{{ containers_file }}"
    regexp: '^(\s*ceph_tag:).*'
    replace: "\\1 {{ docker_ceph_tag }}"
  when: docker_ceph_tag is defined
