---
images_working_dir: "{{ ansible_user_dir }}/workspace"
images_destroy_working_dir: true
build_image_isolated: true
build_isolation_image_url: https://images.rdoproject.org/CentOS-7-x86_64-GenericCloud.qcow2
cleanup_images_working_dir: false
skip_build_images: true
build_isolation_image:
  name: isolation-image
  url: "{{ build_isolation_image_url }}"
  type: qcow2
build_undercloud: true
overcloud_as_undercloud: true
overcloud_repo_paths:
  - "/etc/yum.repos.d/delorean*"
  - "/etc/yum.repos.d/quickstart-*"
  - "{% if ansible_distribution_major_version is version('9', '>=') -%}/etc/yum.repos.d/centos.repo{% endif %}"
  - "{% if job is defined and job.component is defined -%}/etc/yum.repos.d/*-component.repo{%- endif -%}"
