---
# Containers images used in deployment
tripleo_iscsid_image: "{{ docker_registry_host }}/{{ docker_registry_namespace }}/openstack-iscsid:{{ docker_image_tag }}"
tripleo_logrotate_crond_image: "{{ docker_registry_host }}/{{ docker_registry_namespace }}/openstack-cron:{{ docker_image_tag }}"
tripleo_nova_compute_container_image: "{{ docker_registry_host }}/{{ docker_registry_namespace }}/openstack-nova-compute:{{ docker_image_tag }}"
tripleo_nova_libvirt_container_image: "{{ docker_registry_host }}/{{ docker_registry_namespace }}/openstack-nova-libvirt:{{ docker_image_tag }}"
tripleo_ovn_controller_image: "{{ docker_registry_host }}/{{ docker_registry_namespace }}/openstack-ovn-controller:{{ docker_image_tag }}"

# tripleo-standalone-vars script related vars
tripleo_standalone_vars: "/home/{{ ansible_user }}/src/opendev.org/openstack/tripleo-ansible/scripts/tripleo-standalone-vars"
config_download_dir: "/home/{{ ansible_user }}/tripleo-deploy"
role_type: "Standalone"
target_host: undercloud

timestamper_cmd: >-
    | awk '{ print strftime("%Y-%m-%d %H:%M:%S |"), $0; fflush(); }'

# Vars required for compute service deployment
tripleo_network_config_template: templates/ci/multinode.j2
neutron_public_interface_name: eth0
tripleo_selinux_mode: permissive
tripleo_hosts_entries_overcloud_hosts_entries:
  - 192.168.24.1 standalone.ctlplane.localdomain standalone.ctlplane
tripleo_container_registry_insecure_registries:
  - "{{ docker_registry_host }}"

# VIP of the standalone
ctlplane_ip: 192.168.24.3

# Vars needed when allinone compute deployment is done
ctlplane_dns_nameservers:
  - 127.0.0.1
  - 1.1.1.1
dns_search_domains: []
tripleo_ovn_dbs:
  - 192.168.24.1

# Values for validation
tempest_cidr: '192.168.24.0/24'
