---
- name: Set proper container params before deploying standalone
  include_role:
    name: container-prep

- name: Deploy Standalone
  include_role:
    name: standalone

- import_tasks: generate_tripleo_standalone_vars.yml
