---
tobiko_config: true
tobiko_run: true

tobiko_envlist: "scenario"
tobiko_extra_args: ""
tobiko_config_dir: "{{ working_dir }}/.tobiko"
tobiko_config_file: "tobiko.conf"

tobiko_log_dir: "{{ working_dir }}/.tobiko"
tobiko_log_file_base: "tobiko"
tobiko_key_file_name: "~/.ssh/id_rsa"

tobiko_floating_ip_network: "public"
public_network_type: "flat"
public_physical_network: datacentre
public_segmentation_id: ''
floating_ip_cidr: "{{ undercloud_network_cidr }}"
public_network_pool_start: "{{ floating_ip_cidr|nthhost(100) }}"
public_network_pool_end: "{{ floating_ip_cidr|nthhost(120) }}"
public_network_gateway: "{{ floating_ip_cidr|nthhost(1) }}"

python_package_prefix: "python"
