---
- name: Copy stackrc created at the UC user $HOME to the working dir
  tags:
    - undercloud-post-install
  copy:
    src: /home/{{ undercloud_user }}/stackrc
    dest: "{{ working_dir }}/stackrc"
    owner: "{{ undercloud_user }}"
    remote_src: true
    mode: 0640
  become: true
