---
# This makes the overcloudrc file available locally.  This file
# contains credentials for accessing OpenStack API services on the
# overcloud.
- name: Copy overcloudrc to ansible host
  fetch:
    flat: true
    src: "{{ stack_name }}rc"
    dest: "{{ local_working_dir }}/{{ stack_name }}rc"

- name: Run post-deploy script
  shell: >
    set -o pipefail &&
    {{ working_dir }}/{{ stack_name }}-deploy-post.sh 2>&1 {{ timestamper_cmd }} >
    {{ post_deploy_log }}
  changed_when: true
