---
- when: update_containers|bool
  block:

    - name: Update pip
      # noqa 403
      pip:
        name: pip
        state: latest
        extra_args: --upgrade
      become: true

    - name: Pip install container-check
      # noqa 403
      pip:
        name: container-check
        state: latest
        extra_args: --upgrade
      become: true

- name: Prepare for the containerized deployment
  shell: >
    set -o pipefail &&
    {{ working_dir }}/{{ overcloud_prep_containers_script }} 2>&1 {{ timestamper_cmd }} >
    {{ overcloud_prep_containers_log }}
