---

overcloud_prep_images_script: overcloud-prep-images.sh.j2
overcloud_prep_images_log: "{{ working_dir }}/overcloud_prep_images.log"
overcloud_introspect_script: overcloud-introspect.sh.j2
overcloud_introspect_script_log: "{{ working_dir }}/overcloud_introspect.log"
download_overcloud_image_script: download-overcloud-image.sh.j2
download_overcloud_image_log: "{{ working_dir }}/download_overcloud_image.log"
overcloud_image_upload_script: overcloud-image-upload.sh.j2
overcloud_image_upload_log: "{{ working_dir }}/overcloud_image_upload.log"
overcloud_glance_image_upload_script: overcloud-glance-image-upload.sh.j2
overcloud_glance_image_upload_log: "{{ working_dir }}/overcloud_glance_image_upload.log"
overcloud_list_flavors_log: "{{ working_dir }}/overcloud_list_flavors.log"
overcloud_list_flavors_script: overcloud-list-flavors.sh.j2
overcloud_import_nodes_script: overcloud-import-nodes.sh.j2
overcloud_import_nodes_log: "{{ working_dir }}/overcloud_import_nodes.log"
root_device_size_script: root-device-size.sh.j2
root_device_size_log: "{{ working_dir }}/root_device_size.log"
root_device_hints_script: root-device-hints.sh.j2
root_device_hints_log: "{{ working_dir }}/root_device_hints.log"
inject_ara_script: inject-ara.sh.j2
inject_ara_log: "{{ working_dir }}/inject_ara.log"

step_overcloud_image: true
step_glance_upload: false
step_register: true
step_introspect: false
step_introspect_debug: false
step_introspect_debug_tcpdump_log: "{{ working_dir }}/overcloud_prep_images_introspection_debug.pcap.log"
step_introspect_debug_tcpdump_ports:
  - 67
  - 68
  - 69
  - 623
step_introspect_with_retry: false
step_install_undercloud: true
step_root_device_size: false
disk_root_device_size: 1843
step_root_device_hints: false
root_device_hints: []

download_overcloud_image: false
