---
- name: ensure public firewalld services are added
  become: true
  firewalld:
    zone: public
    service: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - tftp
    - dhcp
    - dhcpv6
    - dns
