---
driver:
  name: docker
log: true
platforms:
  - name: instance
    image: centos:7
provisioner:
  name: ansible
  log: true
  env:
    # ANSIBLE_STDOUT_CALLBACK: yaml
    # hack to make it find 'common' role from tq
    ANSIBLE_ROLES_PATH: "${ANSIBLE_ROLES_PATH}:${MOLECULE_SCENARIO_DIRECTORY}/../../../../../tripleo-quickstart/roles"
verifier:
  name: ansible
