---
# https://launchpad.net/bugs/1763776
- name: Add a unique hostname to /etc/hosts resolved to the first IPv4 available
  become: true
  lineinfile:
    dest: /etc/hosts
    state: present
    insertafter: EOF
    line: "{{ ansible_all_ipv4_addresses | first }} {{ ansible_hostname }}-unique"
  when: tripleo_set_unique_hostname|default(false)|bool

- name: Override containerized undercloud CI hostname for tripleo client
  when:
    - undercloud_undercloud_hostname is not defined
  block:
    - name: set fact for undercloud_fqdn override when undercloud_cloud_domain was provided
      set_fact:
        undercloud_fqdn: "{{ ansible_hostname }}.{{ undercloud_cloud_domain }}"
      when:
        - undercloud_cloud_domain is defined

    - name: set fact for undercloud_fqdn override when we have a domain
      set_fact:
        undercloud_fqdn: "{{ ansible_fqdn }}"
      when:
        - ansible_domain|default("") != ""
        - undercloud_cloud_domain is not defined

    - name: set fact for undercloud_fqdn override when we don't have a domain
      set_fact:
        undercloud_fqdn: "{{ ansible_hostname }}.ooo.test"
      when:
        - ansible_domain|default("") == ""
        - undercloud_cloud_domain is not defined

    - name: Set fact for undercloud_hostname override
      set_fact:
        cacheable: true
        undercloud_undercloud_hostname: "{{ undercloud_fqdn }}"
