---
# tasks file for undercloud-setup
# Add a non-root user
- name: Including non_root_user_setup tasks list
  include: non_root_user_setup.yml
  when: non_root_user_setup|bool

- name: Including ovb_setup_connectivity tasks list
  include: ovb_setup_connectivity.yml
  when: ovb_setup_connectivity|bool

- name: Including repo-setup role
  include_role:
    name: repo-setup

- name: Run atop for monitoring
  include: atop.yml

# to_build is enabled via featureset files or featureset overrides
- name: Set variables for gating repos for ovb jobs
  set_fact:
    artg_repos_dir: "{{ repo_clone_dir|default('/opt/stack/new') }}"
    ib_create_web_repo: "{{ to_build|default(false)|bool }}"
    cacheable: true
  when: to_build|default(false)|bool
  tags:
    - build

- name: Run DLRN gate role
  vars:
    artg_compressed_gating_repo: "${HOME}/gating_repo.tar.gz"
  include_role:
    name: build-test-packages
  tags:
    - build

- name: Install gated repo
  when: compressed_gating_repo is defined
  include_role:
    name: install-built-repo
  tags:
    - build

- name: Including package_installs tasks
  include: package_installs.yml
  when: package_installs|bool

- name: Including vxlan_networking tasks
  include: vxlan_networking.yml
  when: vxlan_networking|bool or toci_vxlan_networking|bool

- name: Including hostname tasks
  include: hostname.yml
  when: hostname_correction|bool or step_set_undercloud_hostname|bool

- name: Include ansible.cfg configuration for the undercloud / node
  include: ansible_cfg.yml
  when:
    - undercloud_ansible_cfg|bool and undercloud_ara|bool
