---
- name: gather facts used by role
  setup:
    gather_subset: "!min,python,processor"
  when: >
    ansible_python is not defined or
    ansible_processor_vcpus is not defined

- name: set python_cmd
  set_fact:
    python_cmd: "python{{ ansible_python.version.major }}"
    cacheable: true
  when: python_cmd is not defined

- name: change python_package_prefix for python > 2
  set_fact:
    python_package_prefix: "python{{ ansible_python.version.major }}"
    cacheable: true
  when: ansible_python.version.major > 2

- include: prepare-tobiko.yml
  when: tobiko_config|bool
  tags:
    - prepare-tobiko

- include: run-tobiko.yml
  when: tobiko_run|bool
  tags:
    - tobiko-run

- include: tobiko-results.yml
  when: tobiko_run|bool
  tags:
    - tobiko-results
