---

network_isolation: true
network_isolation_type: single-nic-vlans  # multiple-nics, bond-with-vlans, public-bond
network_environment_file: network-environment.yaml.j2

external_network_cidr: 192.168.23.0/24
undercloud_external_network_cidr: >-
  {%- if overcloud_ipv6|bool %}2001:db8:fd00:1000::/64{% else %}10.0.0.1/24{% endif -%}
overcloud_dns_servers: ['{{ external_network_cidr|nthhost(1) }}']

overcloud_public_vip: "{{ undercloud_external_network_cidr|nthhost(5) }}"
ssl_overcloud: false

network_environment_args:
  ExternalNetCidr: "{{ undercloud_external_network_cidr }}"
  ExternalInterfaceDefaultRoute: "{{ undercloud_external_network_cidr|nthhost(1) }}"
  ExternalAllocationPools: >
    [{'start': '{{ undercloud_external_network_cidr|nthhost(4) }}',
    'end': '{{ undercloud_external_network_cidr|nthhost(250) }}'}]
  NeutronExternalNetworkBridge: ""
  ControlPlaneSubnetCidr: "{{ undercloud_network_cidr|ipaddr('prefix') }}"
  ControlPlaneDefaultRoute: "{{ undercloud_network_cidr|nthhost(1) }}"
  EC2MetadataIp: "{{ undercloud_network_cidr|nthhost(1) }}"
  DnsServers: "{{ overcloud_dns_servers }}"

public_virtual_fixed_ips:
  PublicVirtualFixedIPs: >
    [{'ip_address':'{{ overcloud_public_vip }}'}]

undercloud_type: virtual
baremetal_instackenv: "{{ working_dir }}/instackenv.json"
baremetal_network_environment: "{{ working_dir }}/network-isolation.yml"

overcloud_custom_tht_script: custom-tht-script.sh.j2
overcloud_custom_tht_log: overcloud_custom_tht_script.log

bond_with_vlans_copy_nic_configs_script: bond-with-vlans-copy-nic-configs.sh.j2
bond_with_vlans_nic_configs_log: bond_with_vlans_nic_configs_script_log

tht_rpm_url: https://trunk.rdoproject.org/centos7-{{ release }}/current/

overcloud_prep_post_hook_script: ""

# The `network_data_details` var when defined can be used to copy custom network_data.yaml in
# zuul/stack user home directory. By default for ci use case we utilize tht ci/network_data.yaml:-
# https://github.com/openstack/tripleo-heat-templates/blob/master/ci/network_data.yaml
# In baremetal environment we have to create our own custom network_data.yaml as per
# network layout, details on how to create this file can be found at:-
# https://docs.openstack.org/project-deploy-guide/tripleo-docs/latest/deployment/network_v2.html#pre-provision-networks
# network_data_details:
#  - name: External
#    name_lower: external
#    vip: true
#    mtu: 1500
#    subnets:
#      external_subnet:
#        ip_subnet: 10.0.0.0/24
#        allocation_pools:
#          - start: 10.0.0.4
#            end: 10.0.0.250
#        gateway_ip: 10.0.0.1
#        vlan: 10

# The `network_vip_details` var when defined can be use to create custom vip_data.yaml in zuul
# zuul/stack home directory. By default for ci use case we utilize tht ci/vip_data.yaml:-
# https://github.com/openstack/tripleo-heat-templates/blob/master/ci/vip_data.yaml
# In baremetal environment we have to create our own custom vip_data.yaml as per
# network layout,  details on how to create this file can be found at:-
# https://docs.openstack.org/project-deploy-guide/tripleo-docs/latest/deployment/network_v2.html#pre-provision-network-virtual-ips
# network_vip_details:
#  - network: ctlplane
#    dns_name: overcloud
#  - network: external
#    dns_name: overcloud
#  - network: internal_api
#    dns_name: overcloud
#  - network: storage
#    dns_name: overcloud
#  - network: storage_mgmt
#    dns_name: overcloud
