---
- name: Cloning tempest from openstack repository
  git:
    repo: 'https://opendev.org/openstack/tempest'
    dest: '{{ working_dir }}/tempest_git'
    version: '{{ tempest_version }}'

- name: Cloning python-tempestconf
  git:
    repo: 'https://opendev.org/openinfra/python-tempestconf'
    dest: '{{ working_dir }}/tempestconf_git'
    version: '{{ tempest_conf_version }}'

- name: Check if virtualenv is in the system
  command: "{{ python_cmd }} -m virtualenv --version"
  register: virtualenv_exist
  failed_when: false
  changed_when: false

- when: virtualenv_exist.rc != 0
  name: Install virtualenv
  package:
    state: present
    name: >
        {% if ansible_python.version.major == 3 %}
        python3-virtualenv
        {% else %}
        python-virtualenv
        {% endif %}

- name: Clone tempest plugins
  git:
    repo: "{{ item }}"
    dest: "{{ working_dir }}/{{ item.split('/')[-1] }}"
    version: master
  with_items: "{{ tempest_plugins_git }}"
  when:
    - tempest_format == 'venv'

- name: Install packages required for create venv
  package:
    state: present
    name:
      - gcc
      - libffi-devel
      - openssl-devel

- name: Set tempest init command
  set_fact:
    tempest_init: "{{ working_dir }}/tempest_git/tools/with_venv.sh tempest init"

- name: Set tempestconf call
  set_fact:
    tempestconf: >
      {{ working_dir }}/tempest_git/tools/with_venv.sh discover-tempest-config
