---
- name: Install openstack services tempest plugins
  # noqa 403
  package:
    state: latest
    name: "{{ item | regex_replace( '^python[0-9]*-(.*)$', python_package_prefix + '-\\1' ) }}"
  with_items: "{{ tempest_plugins }}"
  become: true
  when: tempest_plugins|length > 0

- name: Install openstack tempest
  package:
    name:
      - openstack-tempest
      - "{{ python_package_prefix }}-junitxml"
    state: present
  become: true

- name: Install python-tempestconf
  package:
    name: "{{ python_package_prefix }}-tempestconf"
    state: present
  become: true

- name: Set tempest init command
  set_fact:
    tempest_init: "tempest init {{ tempest_dir }}"

- name: Set tempestconf call
  set_fact:
    tempestconf: "/usr/bin/discover-tempest-config"
