---
- name: Deploy the undercloud
  hosts: undercloud
  gather_facts: true
  roles:
    - undercloud-deploy
  tags:
    - undercloud-deploy

- name: Validate the undercloud
  hosts: undercloud
  roles:
    - {role: validate-undercloud,
       when: run_validate_undercloud|default(false)|bool}
  tags:
    - validate-undercloud

- name: Download amphora image for octavia
  hosts: undercloud
  gather_facts: false
  tags:
    - octavia
  roles:
    - {role: octavia-amphora-download,
       when: download_amphora is defined and download_amphora|bool}

- name: Build images for quickstart
  hosts: undercloud
  gather_facts: false
  roles:
    - {role: build-images, when: to_build|default(false)|bool}
  tags:
    - get-images
    - images
