---
- name: Deploy the overcloud
  hosts: undercloud
  gather_facts: false
  tasks:
    - name: Deploy the overcloud
      include_role:
        name: overcloud-deploy
      tags:
        - overcloud-deploy
    - name: Check the overcloud_deployment_result.json if this is CI job
      tags:
        - overcloud-deploy
      block:
        - name: ensure the deployment result has been read into memory
          include_vars: "{{ local_working_dir }}/overcloud_deployment_result.json"
          delegate_to: localhost
        # overcloud_deploy_result = ["failed", "passed"]
        - name: did the deployment pass or fail?
          debug: var=overcloud_deploy_result
          failed_when: overcloud_deploy_result == "failed"
          delegate_to: localhost
