---
# First, deploy the undercloud. This will also ensure the inventory is properly
# populated with the subnode-1 host and all the needed data.
- hosts: undercloud
  gather_facts: true
  tags:
    - standalone
  tasks:
    - name: Run External Data Plane management role
      include_role:
        name: external_data_plane_management
        tasks_from: prepare_node.yml

# Now that we have the updated inventory, we can get to subnode-1 using the
# correct data. Let's bootstrap it!
- hosts: subnode-1
  gather_facts: true
  tags:
    - standalone
  tasks:
    - name: Run External Data Plane management role
      include_role:
        name: external_data_plane_management
        tasks_from: prepare_node.yml

# On undercloud:
# + Deploy standalone
# + Deploy the external compute from within the undercloud
# + Validate external compute
- hosts: undercloud
  gather_facts: false
  tags:
    - standalone
  tasks:
    - name: Deploy standalone
      include_role:
        name: external_data_plane_management
        tasks_from: deploy_standalone.yml
    - name: Deploy remote compute
      vars:
        target_host: 'subnode-1'
      include_role:
        name: external_data_plane_management
        tasks_from: compute_services_on_target_host.yml
    - name: Validate EDPM deploy
      vars:
        target_host: 'subnode-1'
      include_role:
        name: external_data_plane_management
        tasks_from: validate_edpm.yml
