---
- name: Add the overcloud nodes to the generated inventory
  hosts: undercloud
  gather_facts: true
  tags:
    - standalone
  vars:
    inventory: multinode
  roles:
    - tripleo-inventory

- name: Enable nested virtualization on the host
  hosts: undercloud
  gather_facts: true
  roles:
    - parts/kvm
  tags:
    - nested_virt

- name: Prepare the undercloud for installation
  hosts: undercloud
  roles:
    - undercloud-setup
  tags:
    - standalone

- name: Download amphora image for octavia
  hosts: undercloud
  gather_facts: false
  roles:
    - {role: octavia-amphora-download,
       when: download_amphora is defined and download_amphora|bool}
  tags:
    - octavia

# NOTE(aschultz): nested virt causes problems in CI so we default to qemu
# and do not do the dynamic virt lookup.
- name: Deploy Standalone
  hosts: undercloud
  vars:
    standalone_libvirt_type: "{{ standalone_virt_type|default('qemu') }}"
  roles:
    - standalone
  tags:
    - standalone

- name: Run tripleo-validations standalone tests
  import_playbook: validations.yml

- name: Validate the undercloud
  hosts: undercloud
  gather_facts: false
  roles:
    - {role: validate-services, when: validate_services|default(false)|bool}
  tags:
    - standalone

# Per https://bugs.launchpad.net/tripleo/+bug/1903993 we need to reduce the
# standalone-upgrade runtime. If this is upgrade job fs56 skip tempest include.
- name: Validate the deployment
  hosts: undercloud
  # Note(chkumar246): Moved the os_tempest related var at the top
  # of play level in order to have scope for the whole of the play
  # https://bugs.launchpad.net/tripleo/+bug/1838496
  vars:
    tempest_install_method: distro
    tempest_cloud_name: 'standalone'
  tasks:
    - include_tasks: tasks/tempest.yml
      when:
        - job is undefined or (job is defined and
          job.featureset is defined and job.featureset != '056')
        - use_os_tempest | default(true)
        - not job.skip_os_tempest|default(false)
  environment:
    # Disable ssl warnings
    CURL_CA_BUNDLE: ""
  tags:
    - standalone
