---
- name: Add the overcloud nodes to the generated inventory
  hosts: undercloud
  gather_facts: true
  tags:
    - standalone
  vars:
    inventory: multinode
  roles:
    - tripleo-inventory

- name: Enable nested virtualization on the host
  hosts: undercloud
  gather_facts: true
  roles:
    - parts/kvm
  tags:
    - nested_virt

- name: Prepare the undercloud for installation
  hosts: undercloud
  roles:
    - undercloud-setup
  tags:
    - standalone

- name: Test available repos for repoclosure
  hosts: undercloud
  roles:
    - repoclosure
  tags:
    - standalone
