---
- name: Add the overcloud nodes to the generated inventory
  hosts: undercloud
  gather_facts: true
  tags:
    - overcloud-deploy
  vars:
    inventory: multinode_mixed_os
  roles:
    - tripleo-inventory

- name: Create configs on subnodes
  hosts: overcloud_compute
  roles:
    - role: repo-setup
      when: not mixed_upgrade|default(false)|bool
  tasks:
    - name: Create a clean hosts file on subnodes
      copy:
        dest: /etc/hosts
        content: |
          127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4
          ::1        localhost localhost.localdomain localhost6 localhost6.localdomain6
      become: true

    - name: Run atop on overcloud node if configured
      include_role:
        name: undercloud-setup
        tasks_from: atop

  tags:
    - undercloud-setup
