---

##########################
# Prepare for deployment #
##########################

# From tripleo-quickstart/playbooks
- import_playbook: quickstart.yml
- import_playbook: multinode-undercloud.yml
- import_playbook: multinode-overcloud-prep.yml

##################################
# Deploy First stack - overcloud #
##################################

- name: Deploy the overcloud
  hosts: undercloud
  gather_facts: false
  environment:
    TRIPLEO_ROOT: "{{ lookup('env','TRIPLEO_ROOT') }}"
  tasks:
    - name: Deploy the overcloud
      include_role:
        name: overcloud-deploy

    - name: Check the overcloud_deployment_result.json if this is CI job
      tags:
        - overcloud-deploy
      block:
        - name: ensure the deployment result has been read into memory
          include_vars: "{{ local_working_dir }}/overcloud_deployment_result.json"
          delegate_to: localhost
        # overcloud_deploy_result = ["failed", "passed"]
        - name: did the deployment pass or fail?
          debug: var=overcloud_deploy_result
          failed_when: overcloud_deploy_result == "failed"
          delegate_to: localhost

#######################################
# Deploy Second stack - overcloud-two #
#######################################
- name: Deploy the second overcloud
  hosts: undercloud
  gather_facts: false
  environment:
    TRIPLEO_ROOT: "{{ lookup('env','TRIPLEO_ROOT') }}"
  vars:
    stack_name: "overcloud-two"
    overcloud_cloud_name: "{{ stack_name }}.localdomain"
    overcloud_cloud_name_internal: "{{ stack_name }}.internalapi.localdomain"
    overcloud_cloud_name_storage: "{{ stack_name }}.storage.localdomain"
    overcloud_cloud_name_storage_management: "{{ stack_name }}.storagemgmt.localdomain"
    overcloud_cloud_name_ctlplane: "{{ stack_name }}.ctlplane.localdomain"
  tasks:
    - name: Deploy the second overcloud
      include_role:
        name: overcloud-deploy

    - name: Check the overcloud_deployment_result.json if this is CI job
      tags:
        - overcloud-deploy
      block:
        - name: ensure the deployment result has been read into memory
          include_vars: "{{ local_working_dir }}/overcloud_deployment_result.json"
          delegate_to: localhost
        # overcloud_deploy_result = ["failed", "passed"]
        - name: did the deployment pass or fail?
          debug: var=overcloud_deploy_result
          failed_when: overcloud_deploy_result == "failed"
          delegate_to: localhost

######################################
# Run tempest on overcloud-two stack #
######################################

# From tripleo-quickstart/playbooks
- import_playbook: multinode-validate.yml
  vars:
    tempest_cloud_name: 'overcloud-two'
