---
- name: Run overcloud prep config
  hosts: undercloud
  gather_facts: false
  roles:
    - role: overcloud-prep-config
      # only run when we know we have to, save time otherwise
      when: mixed_upgrade|default(false)|bool
  tags:
    - overcloud-prep-config

- name: Run overcloud prep roles
  hosts: undercloud
  gather_facts: false
  roles:
    - {role: overcloud-prep-images,
       step_overcloud_image: false,
       step_glance_upload: true,
       step_register: false}

- name: Prepare for containerized deployment
  hosts: undercloud
  gather_facts: false
  tags:
    - overcloud-prep-containers
  roles:
    - role: overcloud-prep-containers
      use_overcloud_mixed_upgrade: "{{ mixed_upgrade|default(false) }}"

- name: Ensure openvswitch is started and enabled
  hosts: overcloud
  tags:
    - overcloud-deploy
  tasks:
    - name: Ensure openvswitch is started and enabled
      become: true
      service:
        name: openvswitch
        state: started
        enabled: true
