---
- name: setup dstat performance monitoring
  hosts: overcloud
  tags:
    - overcloud-validate
  roles:
    - {role: validate-perf,
       when: validate_performance|bool and use_os_tempest | default(true) | bool}
  ignore_errors: true

# Validate the deployment
- name: validate the overcloud
  hosts: undercloud
  tags:
    - overcloud-validate
    - undercloud-validate
  gather_facts: false
  roles:
    - {role: validate-services, when: validate_services|default(false)|bool}

- name: Validate the deployment
  hosts: undercloud
  # Note(chkumar246): Moved the os_tempest related var at the top
  # of play level in order to have scope for the whole of the play
  # https://bugs.launchpad.net/tripleo/+bug/1838496
  vars:
    tempest_install_method: distro
    tempest_cloud_name: 'overcloud'
    tempest_cidr: '192.168.24.0/24'
  tasks:
    - include_tasks: tasks/tempest.yml
      when: use_os_tempest | default(true) | bool
  environment:
    # Disable ssl waarnings
    CURL_CA_BUNDLE: ""
  tags:
    - overcloud-validate
    - undercloud-validate
