---
- import_playbook: ovb-setup.yml
- import_playbook: baremetal-full-undercloud.yml
- import_playbook: baremetal-full-overcloud-prep.yml
- import_playbook: baremetal-full-overcloud.yml
- import_playbook: validations.yml
- import_playbook: baremetal-full-overcloud-validate.yml
  when: job.enable_overcloud_validate|default(true)|bool
