---
# Prepare any additional configuration files required by the overcloud
- name: Prepare configuration files for the overcloud deployment
  hosts: undercloud
  gather_facts: false
  tags:
    - overcloud-prep-config
  roles:
    - overcloud-prep-config

# Prepare the overcloud for a containerized deployment
- name: Prepare overcloud containers
  hosts: undercloud
  gather_facts: false
  tags:
    - overcloud-prep-containers
  roles:
    - overcloud-prep-containers

# Prepare the overcloud images for deployment
- name: Prepare the overcloud images for deployment
  hosts: undercloud
  gather_facts: false
  tags:
    - overcloud-prep-images
  roles:
    - overcloud-prep-images

# Prepare the overcloud flavor configuration
- name: Prepare overcloud flavors
  hosts: undercloud
  gather_facts: false
  tags:
    - overcloud-prep-flavors
  roles:
    - {role: overcloud-prep-flavors,
       when: step_overcloud_prep_flavors|bool and undercloud_enable_nova|bool}

# Prepare the undercloud networks for the overcloud deployment
- name: Prepare the undercloud networks for the overcloud deployment
  hosts: undercloud
  gather_facts: false
  tags:
    - overcloud-prep-network
  roles:
    - overcloud-prep-network

- name: Prepare the SSL Configuration for the overcloud deployment
  hosts: undercloud
  gather_facts: false
  tags:
    - overcloud-scripts
    - overcloud-ssl
  roles:
    - {role: overcloud-ssl}
