---
# Validate the deployment
- name: setup dstat performance monitoring
  hosts: overcloud
  tags:
    - overcloud-validate
  roles:
    - {role: validate-perf,
       when: validate_performance|bool and use_os_tempest | default(true) | bool}
  ignore_errors: true

# Execute tempest against the overcloud deployment
- name: Validate the deployment
  hosts: undercloud
  tasks:
    - include_tasks: tasks/tempest.yml
      vars:
        tempest_install_method: distro
        tempest_cloud_name: 'overcloud'
      when: use_os_tempest | default(true)
  environment:
    # Disable ssl waarnings
    CURL_CA_BUNDLE: ""
  tags:
    - overcloud-validate

# Ensure services and containers are OK
- name: Execute simple service and container validations
  hosts:
    - undercloud
    - overcloud
  tags:
    - overcloud-validate
    - undercloud-validate
  gather_facts: false
  roles:
    - {role: validate-services, when: validate_services|default(false)|bool}
