---
- include: quickstart.yml

# setup for the undercloud
- name: Prepare the node for installation
  hosts: undercloud
  gather_facts: false
  tags:
    - standalone
  roles:
    - undercloud-setup

- name: Add remove ens3 if not required
  hosts: undercloud
  gather_facts: true
  tasks:
    - include_role:
        name: baremetal-prep-virthost
        tasks_from: remove_ens3.yml
      when:
        - ansible_distribution == 'CentOS'
        - ansible_distribution_major_version|int >= 8

- name: Gather facts
  hosts: undercloud
  become: false
  tags:
    - standalone
  tasks:
    - name: Ensure all facts are gathered
      setup:

# Deploy the standalone
- name: Deploy the standalone
  hosts: undercloud
  gather_facts: true
  tags:
    - standalone
  roles:
    - standalone

- name: Validate the undercloud
  hosts: undercloud
  gather_facts: false
  roles:
    - {role: validate-services, when: validate_services|default(false)|bool}
  tags:
    - standalone

- name: Validate the deployment
  hosts: undercloud
  # Note(chkumar246): Moved the os_tempest related var at the top
  # of play level in order to have scope for the whole of the play
  # https://bugs.launchpad.net/tripleo/+bug/1838496

  vars:
    tempest_install_method: distro
    tempest_cloud_name: 'standalone'
  tasks:
    - include_tasks: tasks/tempest.yml
      when: use_os_tempest | default(true)
  environment:
    # Disable ssl warnings
    CURL_CA_BUNDLE: ""
  tags:
    - standalone
