---
# Deploy the overcloud
- name: Deploy the overcloud
  hosts: undercloud
  gather_facts: true
  tags:
    - overcloud-deploy
  roles:
    - overcloud-deploy

- name: Add the overcloud nodes to the generated inventory
  hosts: undercloud
  gather_facts: true
  tags:
    - overcloud-deploy
    - overcloud-inventory
  vars:
    inventory: all
  roles:
    - tripleo-inventory

# Check the results of the deployment, note after inventory has executed
- name: Check the result of the deployment
  hosts: undercloud
  tags:
    - overcloud-deploy
    - overcloud-check
  tasks:
    - name: Check the overcloud_deployment_result.json if this is CI job
      tags:
        - overcloud-deploy
      block:
        - name: ensure the deployment result has been read into memory
          include_vars: "{{ local_working_dir }}/overcloud_deployment_result.json"
          delegate_to: localhost
        # overcloud_deploy_result = ["failed", "passed"]
        - name: did the deployment pass or fail?
          debug: var=overcloud_deploy_result
          failed_when: overcloud_deploy_result == "failed"
          delegate_to: localhost
