---
- name: Execute Validations Framework tests
  hosts: undercloud
  gather_facts: true
  vars:
    inventory: "{{ job.validations_inventory|default('tripleo-deploy/tripleo-ansible-inventory.yaml') }}"
    vf_log_dir: "/var/log/validations"
  tags:
    - overcloud-deploy
    - undercloud-deploy
    - standalone
  tasks:
    - include_role:
        name: validations
      when:
        - job.enable_validation|default(false)|bool
